spring:
  application:
    name: employee-zuul-service

server:
  port: 8089
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka

zuul:
  routes:
    producer:
      url: http://localhost:8080

